server:
  port: 8082

jwt:
  password:
    encoder:
      secret: F2K2DZ82odq$13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      key-length: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f86df20a499a7d3f91ff2a7c
  expiration: 7200
  issuer: SECURITY_SERVICE


springdoc:
  swagger-ui:
    enabled: true
    path: /api/v1/swagger-ui.html
  api-docs:
    path: /v3/api-docs
    enabled: true
  packages-to-scan: com.example.security_service.controller

logging:
  level:
    org.springdoc: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      simple:
        enabled: true