version: '3.8'

services:
  postgres-user:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-user:5432/user_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 8081
    depends_on:
      postgres-user:
        condition: service_healthy

  auth-service:
    build: ./auth-service
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_CLOUD_GATEWAY_ROUTES_USER-SERVICE_URI: http://user-service:8081
      SPRING_CLOUD_GATEWAY_ROUTES_AUTH-SERVICE_URI: http://auth-service:8082
    depends_on:
      - user-service
      - auth-service

volumes:
  postgres_user_data: