version: '3.8'

services:
  postgres-user:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d user_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s


  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data
      - ./minio/init:/docker-entrypoint-init.d
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  user-service:
    build: ./user-service
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-user:5432/user_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SERVER_PORT: 8081
    depends_on:
      postgres-user:
        condition: service_healthy

  auth-service:
    build: ./auth-service
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082

  image-service:
    build: ./image-service
    ports:
      - "8083:8083"
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_NAME: images
      SERVER_PORT: 8083
    depends_on:
      minio:
        condition: service_healthy

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_CLOUD_GATEWAY_ROUTES_USER-SERVICE_URI: http://user-service:8084
      SPRING_CLOUD_GATEWAY_ROUTES_AUTH-SERVICE_URI: http://auth-service:8082
    depends_on:
      - user-service
      - auth-service

volumes:
  postgres_user_data:
  minio_data: