server:
  port: 8084

spring:
  hikari:
    connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://postgres-user:5432/user_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  swagger-ui:
    enabled: true
    path: /api/v1/swagger-ui.html
  api-docs:
    path: /v3/api-docs
    enabled: true
  packages-to-scan: com.example.user_service.controller

logging:
  level:
    org.springdoc: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      simple:
        enabled: true
